config/routes.rb
Rails.application.routes.draw do
  root "pictures#index"
  devise_for :users
  resources :pictures

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    before_action :update_allowed_parameters, if: :devise_controller?
    before_action :authenticate_user!

    rescue_from ActionController::RoutingError, with: :not_found
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    def not_found()
      render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
  
    def update_allowed_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :current_password)}
    end

end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
  
  def index
    @pictures = Picture.where(:user_id => current_user.id)
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to @picture
    else
      render :new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end 

  def update
    @picture = Picture.find(params[:id])

    if @picture.update(article_params)
      redirect_to @picture
    else
      render :edit
    end
  end

  private
    def picture_params
      params.require(:picture).permit(:title, :description, :image)
    end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  def index

    title_search = params[:search]

    if(! title_search.nil? && !title_search.to_s.strip.empty?)
      @search = title_search
      @pictures = Picture.where(["user_id = ? AND title LIKE (?)", current_user.id, "%#{title_search}%"])
    else
      @pictures = Picture.where(:user_id => current_user.id)
      @search= nil
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to @picture
    else
      render :new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end 

  def update
    @picture = Picture.find(params[:id])

    if @picture.update(picture_params)
      redirect_to @picture
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to root_path
  end

  private
    def picture_params
      params.require(:picture).permit(:title, :description, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageRepository</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="picture-form-wrapper">

    <h2><%= title %></h2>

    <%= form_with model: picture do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="field">
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>

    <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>

    <div class="field">
        <%= f.submit %>
    </div>
    </div>
    <% end %>
</div>

app/views/pictures/edit.html.erb
<%= render "form", picture: @picture, title: "Edit Image" %>

app/views/pictures/index.html.erb
<h1 class="title">Gallery</h1>

<a style="left:30px" class="menu-button" href = "/pictures/new"> New Photo </a>
<%= link_to "Sign out", destroy_user_session_path, :class => "menu-button sign-out", :method => :delete %>

<br>

<div class = "search-box">
  <form action = "/">
    <input type="text" value = "<%=@search%>" name="search" placeholder="Search by title...">
  </form>
</div>

<div class="gallery-wrapper">
  <div class = "gallery">
    <% @pictures.each do |pic| %>
    <div class = "image-card">
    <a href="/pictures/ <%= pic.id %>">
      <%= image_tag pic.image %>
    </a>
      <div>
        <h3 style="text-align:center"><%= pic.title %></a></h3>
        <p style="text-align:center"><%= truncate(pic.description) %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<%= render "form", picture: @picture, title: "Add New Image" %>

app/views/pictures/show.html.erb
<div class = "single_image_card">
    <%= image_tag @picture.image %>
    <h2> <%= @picture.title %></h2>
    <p> <%= @picture.description %></p>

    <a class="link-as-button" href = "/">Back</a>
    <%= link_to "Edit", edit_picture_path(@picture), :class => "link-as-button" %>
    <%= link_to "Delete", picture_path(@picture),
                  method: :delete,
                  :class => "link-as-button",
                  data: { confirm: "Are you sure?" } %>

</div>